SIMILARITY_THRESHOLD = 0.80
DOCUMENT_THRESHOLD = 0.75
QUESTION_SIMILARITY_THRESHOLD = 0.90
BOOST_FACTOR = 0.30
TOP_K_CHUNKS = 2
MAX_WORKERS = 5
MAX_RETRY=3
DEFAULT_DIFFICULTY = "Medium"

LLM_MODEL = "llama-3.3-70b-versatile"
LLM_TEMPERATURE = 0


# Embedding
EMBEDDING_MODEL = "sentence-transformers/all-MiniLM-L6-v2"